### ISSUE TITLE
Trim Leading and Trailing Whitespace - major issue with lessons

### ISSUE THREAD

**Issue by RebeccaOlson** [datacarpentry/OpenRefine-ecology-lesson#255] opened 2021-03-29 15:54 UTC
In the most recent versions of Open Refine (3.4.1 as of today, 20210329), when you upload data to create a new project, the option for "Trim leading and trailing whitespace" is already checked (see screenshot attached). This affects several steps in this lesson. Namely, the clustering step (there are only 2 choices found) and the Split lesson. Step 6 in that lesson does not apply since the missing values no longer exist since you've taken care of them with this option checked.  It also makes the "Trim leading and trailing whitespace" section superfluous.  

Recommendation - add a section to the "Create project" section advising students to uncheck that box for this lesson. 

![openrefine_ecologists_trim_whitespace](https://user-images.githubusercontent.com/44096875/112863899-53729380-9085-11eb-9175-83ac9369c459.JPG)

**Comment by sheshan93** [comment] 2021-04-23 19:44
Just my two cents--if this is now the default, would it perhaps make more sense to alter the affected portions of the lesson? I would think that for novices, it's easier to teach within the system default, unless there is a compelling reason the rest can't be changed. It seems more likely that people uploading data and using OpenRefine for the first time will just leave the trimming of white space as the default, as that is easier. For example, if it were me, I'd think "Great, that's one less step I have to take when I get in to digging with my data." Students may be confused/not understand why we're including a "trim leading and trailing whitespaces" section in the lesson if it's something that can be done automatically at the beginning of the process.

**Comment by drsjford** [comment] 2021-05-14 08:07
We had the same issue in sessions over the last two weeks, made more complicated by the delegates believing the dataset was incorrect.

**Comment by debpaul** [comment] 2021-05-14 14:38
Hm.

- I wonder if this means one could make the point in the spreadsheet lesson. Then refer back to that issue, when moving to this Open Refine step.
- Also, is there any reason ever? why you would Not want to remove / trim leading and trailing whitespaces? Can anyone think of a use case for this?
   - if not, perhaps then just change the lesson as @sheshan93 suggests, adding a step to the lesson that explicitly notes this on the upload step of data into Refine.

**Comment by ljvillanueva** [comment] 2021-05-28 16:02
Duplicate of #245. Please follow discussion there.

**Closed by ljvillanueva** 2021-05-28 16:02 UTC
