### ISSUE TITLE
Submitted by email for instructor training checkout

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/OpenRefine-ecology-lesson#153] opened 2017-09-18 15:40 UTC
In the Filtering & Sorting topic, it might be helpful to add a comment in the Key Point about the fact that unlike spreadsheet programs, accurate sorting does not depend on selecting the entire dataset because OpenRefine is not modifying the raw date. 

In the Examining Numbers topic, the use of scatterplot facets might be confusing for people who don't know what they are. Adding some language like "scatterplots show how one variable (values in a column) is affected by another variable. Both variables need to be numbers (statistical data types are ordinal, interval, or ratio) but cannot be categorical or labels (text fields).

**Comment by ljvillanueva** [comment] 2021-06-11 18:09
First paragraph is a dupe of #76 

Second is dupe of #113 

Closing as part of cleanup.

**Closed by ljvillanueva** 2021-06-11 18:09 UTC
