### ISSUE TITLE
missing solution for scatterplot facet exercise

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/OpenRefine-ecology-lesson#165] opened 2017-12-20 16:36 UTC
Submitted via email. 

To complete my checkout for instructor training, I would like to describe a potential improvement to:
Open Refine for Ecology: Examining Numbers in OpenRefine: Scatterplot facet
My suggestion:

The exercise for the Scatterplot facet does not have a solution associated with it at the moment.
When I was completing the lesson, I didn't know what the answer to question 2 would be and I would have preferred to see the solution.

**Comment by ljvillanueva** [comment] 2021-06-11 18:13
Dupe of #156. Closing.

**Closed by ljvillanueva** 2021-06-11 18:13 UTC
