### ISSUE TITLE
Scatterplot facet lessons

### ISSUE THREAD

**Issue by kta65** [datacarpentry/OpenRefine-ecology-lesson#250] opened 2020-11-04 18:57 UTC
I would like to suggest a small addition to the Data Cleaning with OpenRefine for Ecologists section 4. Examining numbers in OpenRefine. 

The section on Scatterplot facets is really lacking in information on what a Scatterplot facet is and how to use them. Unless the instructor has used the Scatterplot function multiple times before, the instructions in the lesson don't really provide enough information. The information on the [Open Refine manual](https://docs.openrefine.org/manual/facets/) section on Scatterplot facets is a lot clearer, and I think it would be useful to incorporate some of this information into the lesson.

**Comment by froggleston** [comment] 2021-03-01 14:40
+1

Just taught the latest materials and I think more detail around the scatterplot facet (and the other graphical facets) would be a good addition. We covered the existing materials in 1hr 45 so I think there is time for a bit of extra detail!

**Comment by ljvillanueva** [comment] 2021-06-11 18:24
Seems to be a dupe of #113. Explanation seems highly needed.

**Closed by ljvillanueva** 2021-06-11 18:24 UTC
